"""empty message

Revision ID: 003360d8432f
Revises: e2cf358eaf5c
Create Date: 2026-03-17 16:48:16.188019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '003360d8432f'
down_revision = 'e2cf358eaf5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('auth_level', sa.Integer(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=mysql.ENUM('General', 'Technology', 'Sports', 'Entertainment', 'Lifestyle', 'Education', 'Finance', 'Fitness', 'Design', 'Worship/Religion', 'Fashion'),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['category_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('category_name',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('General', 'Technology', 'Sports', 'Entertainment', 'Lifestyle', 'Education', 'Finance', 'Fitness', 'Design', 'Worship/Religion', 'Fashion'),
               existing_nullable=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('auth_level')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
