"""empty message

Revision ID: 18d8ea60c3f9
Revises: 
Create Date: 2026-03-15 09:16:52.946525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d8ea60c3f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('adm_email', sa.String(length=100), nullable=False),
    sa.Column('userName', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('lastLogged_in', sa.TIMESTAMP(), nullable=True),
    sa.Column('approval_status', sa.Enum('approved', 'rejected', 'pending'), nullable=True),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('adm_email')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.Enum('General', 'Technology', 'Sports', 'Entertainment', 'Lifestyle', 'Education', 'Finance', 'Fitness', 'Design', 'Worship/Religion'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=45), nullable=True),
    sa.Column('user_fname', sa.String(length=45), nullable=True),
    sa.Column('user_lname', sa.String(length=45), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=255), nullable=True),
    sa.Column('user_Phone', sa.String(length=45), nullable=True),
    sa.Column('user_profilePic', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('community',
    sa.Column('idcommunity', sa.Integer(), nullable=False),
    sa.Column('community_desc', sa.Text(), nullable=True),
    sa.Column('communityname', sa.String(length=45), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('createdByUserId', sa.Integer(), nullable=True),
    sa.Column('admin_userId', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_read', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['admin_userId'], ['admin.id_admin'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['createdByUserId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('idcommunity')
    )
    op.create_table('community_members',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.idcommunity'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('community_id', 'member_id')
    )
    op.create_table('posts',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('post_content', sa.String(length=6200), nullable=True),
    sa.Column('contribution_Count', sa.Integer(), nullable=True),
    sa.Column('post_created', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.idcommunity'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('postId')
    )
    op.create_table('comments',
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('contribution_Content', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_Date', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.postId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('post_image',
    sa.Column('id_image', sa.Integer(), nullable=False),
    sa.Column('image_URL', sa.String(length=45), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.postId'], ),
    sa.PrimaryKeyConstraint('id_image')
    )
    op.create_table('relationship',
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.idcommunity'], ),
    sa.ForeignKeyConstraint(['contribution_id'], ['comments.contribution_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.userId'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.postId'], ),
    sa.PrimaryKeyConstraint('community_id', 'post_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    op.drop_table('post_image')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('community_members')
    op.drop_table('community')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
