"""empty message

Revision ID: c2bd7f3cb95b
Revises: 66e62d6ab0f4
Create Date: 2026-03-19 02:08:01.377801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2bd7f3cb95b'
down_revision = '66e62d6ab0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('auth_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
